# Generated by Django 6.0.6 on 2026-06-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaReparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(default='equipo', max_length=64, unique=True)),
                ('slides', models.JSONField(blank=True, default=dict)),
                ('partes', models.JSONField(blank=True, default=dict)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reparto guía presentación',
                'verbose_name_plural': 'Repartos guía presentación',
            },
        ),
    ]
